export enum TOKEN_ERROR_CODES {
	INVALID_REQUEST = "INVALID_REQUEST",
	INVALID_CLIENT = "INVALID_CLIENT",
	INVALID_GRANT = "INVALID_GRANT",
	UNSUPPORTED_GRANT_TYPE = "UNSUPPORTED_GRANT_TYPE",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	INVALID_ID_TOKEN = "INVALID_ID_TOKEN",
}
