export enum SEND_VERIFICATION_LINK_ERROR_CODES {
	UNDEFINED_ERROR_CODE = "UNDEFINED_ERROR_CODE",
	INVALID_PARAMS = "INVALID_PARAMS",
	BREAKPOINT_NOT_YET_IMPLEMENTED = "BREAKPOINT_NOT_YET_IMPLEMENTED",
	INVALID_USER_PHONE_NUMBER_OR_EMAIL = "INVALID_USER_PHONE_NUMBER_OR_EMAIL",
}
